spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/sample_db
        username: postgres
        password: admin

    jpa:
        hibernate:
            ddl-auto: update
        show-sql: false
        properties:
            '[hibernate.show_sql]': false
            '[hibernate.format_sql]': true
            '[hibernate.use_sql_comments]': true
            '[hibernate.jdbc.time_zone]': UTC
            '[integration.envers.enabled]': true
    flyway:
        enabled: true
        locations: 
            - classpath:/db/migration

problem:
    type-url: http://localhost:8080/problems/help.html
    debug-enabled: false
    stacktrace-enabled: false
    cause-chains-enabled: false

server:
    port: 8080
    #servlet:
        #context-path:

logging:
    file:
        path: logs
        name: ${logging.file.path}/application.log
    level:
        ROOT: info
    logback:
        rollingpolicy:
            clean-history-on-start: true
debug: false

# ===================================================================
# Application specific properties
# Add your own application properties here
# ===================================================================

        